services:
  lazymc:
    container_name: lazymc
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    environment:
      # Point to the service name of the Minecraft server
      SERVER_ADDRESS: mc:25565
      # Required to find the container to manage it
      LAZYMC_GROUP: mc
    restart: unless-stopped
    volumes:
      # you should mount the minecraft server dir under /server, using read only.
      - data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "25565:25565"
  
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      labels: "lazymc.group=mc"
      CF_API_KEY: $$2a$$10$$HEAechUdlU4vqVdmk/IvjO35WAkCfjfr8mGybCrRhRuP0m4aRPIee
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg
      CF_FILENAME_MATCHER: "2.8.7"
      MEMORY: 64G
      restart: no
    volumes:
      - data:/data

volumes:
  data: {}